const { withAppDelegate, withPodfile } = require("expo/config-plugins");

const PODFILE_MARKER_START = "# @generated by withOneMoreIosJsc - start";
const PODFILE_MARKER_END = "# @generated by withOneMoreIosJsc - end";
const PODFILE_ENV = `${PODFILE_MARKER_START}
ENV['USE_THIRD_PARTY_JSC'] = '1'
ENV['USE_HERMES'] = '0'
ENV['RCT_USE_RN_DEP'] = '0'
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'
${PODFILE_MARKER_END}`;

const JSC_IMPORT = "import ReactJSC";
const JSC_FACTORY = `  override func createJSRuntimeFactory() -> JSRuntimeFactoryRef {
    jsrt_create_jsc_factory()
  }`;

function patchPodfile(contents) {
  const withoutExistingBlock = contents.replace(
    new RegExp(`${PODFILE_MARKER_START}[\\s\\S]*?${PODFILE_MARKER_END}\\n*`, "g"),
    "",
  );
  return `${PODFILE_ENV}\n${withoutExistingBlock}`;
}

function patchAppDelegate(contents) {
  let source = contents;

  if (!source.includes(JSC_IMPORT)) {
    const importAnchor = "import ReactAppDependencyProvider";
    if (!source.includes(importAnchor)) {
      throw new Error("Unable to add ReactJSC import to the generated iOS AppDelegate");
    }
    source = source.replace(importAnchor, `${importAnchor}\n${JSC_IMPORT}`);
  }

  if (!source.includes("override func createJSRuntimeFactory()")) {
    const delegateAnchor = "  // Extension point for config-plugins";
    if (!source.includes(delegateAnchor)) {
      throw new Error("Unable to add the JSC runtime factory to the generated iOS AppDelegate");
    }
    source = source.replace(delegateAnchor, `${delegateAnchor}\n\n${JSC_FACTORY}`);
  }

  return source;
}

function withOneMoreIosJsc(config) {
  config = withPodfile(config, (mod) => {
    mod.modResults.contents = patchPodfile(mod.modResults.contents);
    return mod;
  });

  return withAppDelegate(config, (mod) => {
    if (mod.modResults.language !== "swift") {
      throw new Error("OneMore's iOS JSC integration requires a Swift AppDelegate");
    }
    mod.modResults.contents = patchAppDelegate(mod.modResults.contents);
    return mod;
  });
}

module.exports = withOneMoreIosJsc;
module.exports.__test = { patchAppDelegate, patchPodfile };
